# Python program to find the SHA-1 message digest of a file

# importing the hashlib module
import hashlib

def hash_file(filename):
   """"This function returns the SHA-1 hash
   of the file passed into it"""

   # make a hash object
   h = hashlib.sha1()

   # open file for reading in binary mode
   with open(filename,'rb') as file:

       # loop till the end of the file
       chunk = 0
       while chunk != b'':
           # read only 1024 bytes at a time
           chunk = file.read(1024)
           h.update(chunk)

   # return the hex representation of digest
   return h.hexdigest()

message = hash_file("track1.mp3")
print(message)











###In this program, we open the file in binary mode. Hash functions are available in the hashlib module. We loop till the end of the file using a while loop. On reaching the end, we get empty bytes object.

##In each iteration, we only read 1024 bytes (this value can be changed according to our wish) from the file and update the hashing function.

##Finally, we return the digest message in hexadecimal representation using the hexdigest() method.




#this is a demo script ZWA testing rev 1
His is ZWA Test 2 - Deep Dive
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus tristique augue bibendum est placerat auctor non nec urna. Quisque elit tortor, molestie in ligula at, sodales ultrices orci. Nulla facilisi. Proin et nulla maximus, gravida eros ac, consequat turpis. Sed a sapien metus. Donec gravida efficitur arcu et pellentesque. Donec lobortis auctor augue eget rutrum. Etiam varius sem eget leo varius, in maximus ante feugiat. Phasellus eu sollicitudin metus. Fusce eros tortor, aliquet ac lorem in, pretium fringilla sem. Nunc lobortis fermentum sapien, nec porta est iaculis vel. Morbi eget neque id dolor semper eleifend. Ut condimentum, dui at convallis facilisis, augue turpis pretium augue, vel ultricies mi ex vitae nunc. Nulla facilisi.

Praesent ex erat, bibendum at placerat at, tincidunt sed nisi. Ut dapibus a sapien id dictum. Etiam euismod lacus non rhoncus tincidunt. Curabitur vestibulum urna eget risus vestibulum, ac gravida nisi lobortis. Curabitur in laoreet arcu, et vulputate lacus. Morbi vel pulvinar est. Vestibulum tincidunt porttitor convallis. Duis porttitor ac justo et sollicitudin. Mauris ex nisl, cursus in ante ac, maximus ornare dolor. Nulla vulputate nisl eget accumsan fringilla. Nunc hendrerit tristique elit consequat condimentum.

Pellentesque varius felis purus, nec cursus mauris iaculis quis. Integer erat neque, bibendum sed laoreet eu, tempor in velit. Aliquam sagittis tortor non nibh egestas, a feugiat arcu luctus. Pellentesque fermentum condimentum cursus. Ut accumsan orci nec facilisis mollis. Nam porttitor laoreet mattis. Nulla vehicula condimentum neque ac maximus. Suspendisse suscipit lorem mi, ut mollis metus porta vel. Mauris pretium, sem mattis lobortis mattis, enim risus pellentesque dui, eget laoreet libero orci sed orci. Mauris pulvinar sem massa, sed tincidunt neque porta nec. Mauris et lacus ut mauris dapibus faucibus vel et diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam id eleifend augue. Morbi feugiat, nisl vitae pharetra bibendum, enim sapien vestibulum augue, non pretium quam ante pulvinar lacus. Duis fringilla sem vitae blandit blandit. Nunc viverra sed nisi ut bibendum.

Nulla vehicula quam vitae ex molestie elementum. Maecenas ac mattis turpis, et malesuada urna. Praesent dictum lorem vel diam pretium, et pretium libero hendrerit. Donec nec neque id lorem auctor vulputate vel nec nisl. Proin laoreet sapien sit amet enim tempus vestibulum. Quisque eros lacus, congue ac vestibulum commodo, euismod a quam. Integer volutpat lacinia est. Nulla turpis mauris, sodales quis lectus vitae, dictum feugiat arcu. Integer tincidunt ultricies est et accumsan. Donec feugiat dapibus enim, ac ornare tortor sodales in. Aliquam ut consectetur nisl, ut hendrerit ligula. Sed pharetra nec ex viverra aliquet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam finibus viverra mollis. Ut eu justo at massa dictum viverra.

Suspendisse quis sagittis eros. Quisque sodales mi at nisi volutpat tincidunt. In sollicitudin, ipsum quis vestibulum hendrerit, orci urna molestie felis, sed fringilla risus urna et magna. In enim diam, malesuada id venenatis sit amet, consequat vitae neque. Aenean nec bibendum odio, quis consectetur elit. Phasellus in lacus vel mi tempus imperdiet. Nam eget nunc id turpis vestibulum lobortis non vitae quam. Donec laoreet sagittis sem, vel pretium mauris sodales quis. Morbi molestie tempus tristique. Vivamus vitae cursus enim. Donec metus purus, bibendum in odio scelerisque, venenatis laoreet odio.

In mollis felis vel erat efficitur, vel lacinia erat sodales. Sed et sodales tortor, sed scelerisque arcu. Nullam laoreet sapien non aliquam hendrerit. Mauris et sem elementum, vulputate elit tristique, hendrerit odio. Nulla at nibh ac enim auctor pharetra ac nec mi. Morbi gravida nec dui quis volutpat. Sed euismod semper venenatis. Quisque elementum orci id quam blandit pellentesque. Morbi consectetur lectus sem, tincidunt ultricies mi rhoncus vel. Mauris commodo bibendum quam, nec sodales orci placerat nec. Vestibulum vel cursus massa. Phasellus placerat eu mauris commodo dapibus. Praesent id scelerisque nisl. Nunc eleifend sed nibh eu laoreet. Aenean vitae ornare urna, sit amet pretium nisl.

Fusce non condimentum purus. Vestibulum felis dolor, luctus a mauris ac, tincidunt faucibus lorem. Aliquam posuere augue in consectetur fermentum. Donec fermentum orci ut hendrerit consectetur. Curabitur dignissim tempor erat, eget aliquet magna rutrum luctus. Fusce pulvinar finibus vulputate. Phasellus sed dui erat. Cras dolor orci, aliquet eu purus at, pulvinar viverra lectus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed laoreet vulputate elit, at rutrum tellus accumsan a. Etiam iaculis massa ut libero pharetra, quis tempor nisi consectetur. Phasellus elementum leo eu tincidunt ullamcorper. Cras sollicitudin tellus lacus, eu convallis eros aliquam eget. Ut quis ultricies lectus, efficitur efficitur quam.

Aliquam erat volutpat. Sed dapibus ac tellus a accumsan. Nunc at rhoncus dolor. Curabitur et sem vel elit mattis laoreet a non libero. Donec magna elit, vulputate sed nunc in, ultrices bibendum arcu. Etiam tempor vestibulum purus quis mollis. Proin mattis orci sollicitudin urna eleifend malesuada. Proin porta elementum elit, id tempor ipsum gravida vel. Aenean cursus tristique nisl at egestas. Sed ac magna nec metus congue pharetra vel varius dui. Fusce et odio ac enim interdum cursus. Curabitur vehicula sem sit amet efficitur lacinia. Donec eu eros sollicitudin dui tincidunt maximus vehicula ut diam. Morbi euismod et metus non efficitur.

Quisque fringilla quam mi, non rutrum nunc porta id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent et semper lectus. Curabitur porttitor felis interdum turpis dapibus, at consequat erat molestie. Vivamus nunc magna, pharetra quis eros nec, viverra consectetur eros. Etiam porttitor imperdiet risus id iaculis. Maecenas tincidunt arcu ut mauris vestibulum, sed porttitor quam mattis. Sed bibendum, nulla eu elementum ultrices, neque lacus lobortis mi, eu placerat justo quam non nisl. Aenean imperdiet imperdiet tristique. Duis pretium nulla at turpis commodo facilisis.

Donec sagittis justo vel malesuada blandit. Vestibulum tincidunt sem odio, a eleifend erat euismod ac. Praesent et magna orci. Nunc elementum metus erat, sed lobortis libero consequat id. Donec elementum cursus ipsum, at scelerisque nibh vehicula nec. Aenean commodo diam cursus laoreet porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec et bibendum nunc. Nulla viverra consectetur commodo. Nulla dapibus mi egestas risus vulputate consequat. Vestibulum nec bibendum diam.

Quisque vel scelerisque arcu. Ut lorem sem, mattis a mattis non, rhoncus eget sapien. In pharetra, ligula nec scelerisque facilisis, velit orci varius massa, ac vehicula nisl dolor quis felis. Praesent sit amet purus elit. Maecenas blandit lacus dui, nec maximus leo tristique vitae. Vivamus non orci quis elit ullamcorper scelerisque. Phasellus congue a nunc et mattis. Proin pulvinar leo quis odio convallis, id imperdiet sem efficitur. Quisque at mi commodo, efficitur risus quis, pharetra sapien. Morbi ligula risus, pharetra pellentesque pulvinar ut, fermentum ac sapien.

Duis tempus mauris non ex finibus porttitor. Ut rutrum pretium convallis. Ut vel blandit odio, vitae malesuada sem. Praesent molestie molestie neque sed ultrices. Nulla facilisi. Donec arcu massa, accumsan vitae eleifend sit amet, pretium in tortor. Maecenas interdum volutpat sollicitudin. Donec sodales tristique ex, posuere tincidunt est viverra et. Vivamus eget metus nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis massa et sodales tempus. Cras egestas ante vitae ipsum pharetra rutrum. Duis cursus diam sed felis sollicitudin, non porta quam laoreet. Praesent non rhoncus quam. Praesent at placerat orci, eu rutrum mauris.

Suspendisse fermentum, urna id malesuada volutpat, nulla diam varius mauris, eget euismod dolor tortor id augue. Integer suscipit varius magna vitae aliquam. Pellentesque vel sapien eu ligula pulvinar lacinia. Donec sodales nisi quis enim ullamcorper efficitur. Duis nec ante nisi. Nulla sit amet mi eros. Integer non purus turpis. Donec eu est nec nulla tempor facilisis quis et nisl. Nulla convallis, augue at tincidunt posuere, orci nibh ornare tortor, id vulputate augue augue et lacus. Aenean auctor rhoncus dolor, ut hendrerit dui euismod posuere. Nulla rutrum sem elit, non finibus quam venenatis ut. Nullam pretium rhoncus tortor a tempor. Nullam fermentum justo id mattis mollis. Nullam vel ultrices lacus. Nam dapibus vulputate arcu, at feugiat ligula elementum id.

Vivamus non eros iaculis ex tincidunt consequat eu placerat eros. Mauris sodales, odio ut ultrices finibus, nisi velit posuere sem, eget porta ligula erat vitae enim. Vestibulum lobortis tortor eu diam congue auctor. Proin urna eros, rutrum non quam vitae, tincidunt gravida dolor. Nullam sit amet odio a est rhoncus commodo. Morbi pulvinar tellus ut nisi lobortis egestas. Sed consequat elementum nibh, a auctor nunc viverra non. Suspendisse potenti. Morbi vitae velit tempus, efficitur dui at, gravida quam. Duis facilisis sodales dui, et consectetur enim pharetra ac. Quisque eu fermentum risus, a tempus dui. In sed pharetra ante. Donec viverra est lectus, non tristique nulla cursus ac. Donec tortor augue, commodo ullamcorper lacus sit amet, porttitor vulputate sapien. In condimentum non lacus sed malesuada. Nam eget justo ut nibh aliquet gravida.

Donec odio eros, laoreet et ipsum non, fermentum volutpat leo. Phasellus ex ipsum, gravida a pharetra in, consequat vitae nisl. Fusce erat sapien, tristique ac tincidunt sit amet, lobortis nec turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed sit amet enim neque. In hac habitasse platea dictumst. Sed sit amet ipsum semper, facilisis nisi quis, egestas mi. Aenean venenatis purus in libero sagittis, nec interdum est vehicula. Cras finibus nibh vitae quam vulputate blandit. Morbi eu accumsan odio. Donec eu cursus eros. Sed tristique dolor ut gravida bibendum. Duis nec lacus varius, varius dolor nec, volutpat arcu. Proin cursus cursus dolor ullamcorper sodales.

Curabitur blandit consequat gravida. Duis laoreet venenatis justo mollis tempus. Maecenas nec tellus sapien. Nunc pretium mattis sollicitudin. Morbi nec purus sed mi consequat hendrerit. Nulla molestie leo id ipsum eleifend, et gravida mauris sagittis. Nullam non lorem et dolor sollicitudin ornare.

Nullam faucibus metus non massa efficitur, id consectetur nisi elementum. Mauris eu dictum est, sed porta metus. Donec blandit ultrices euismod. Morbi efficitur auctor leo, nec molestie lorem hendrerit sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce quis pharetra eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque eu lacinia ante. Nunc rhoncus tellus ac lacus elementum eleifend. Integer bibendum bibendum ultrices. In pretium, risus at laoreet elementum, nulla magna viverra ante, vel tristique mi nisl nec lacus. Mauris posuere massa et lorem tempus, ut mattis erat congue.

Vivamus hendrerit elit vitae blandit consectetur. Cras vestibulum eget mi eget eleifend. Maecenas blandit tellus et tellus ultricies, ultricies suscipit nunc dapibus. Sed cursus pulvinar pharetra. Etiam facilisis, tortor sed ornare hendrerit, mauris nisl rhoncus tellus, ut varius magna tortor quis massa. Aliquam eget vulputate turpis, congue consequat orci. Curabitur ultricies ultricies diam. Donec quis eros id ligula congue congue. Mauris eu ipsum massa. Pellentesque vitae tempus eros.

Vivamus sit amet diam ac nisl lacinia imperdiet nec eu justo. Phasellus pharetra leo eget purus venenatis sodales. Phasellus interdum convallis bibendum. Cras ultrices ac diam vestibulum egestas. Aenean urna mauris, cursus vel egestas ornare, dictum id elit. Proin dui arcu, ullamcorper et condimentum ut, euismod non massa. Praesent fringilla mauris vel ante malesuada fermentum sed et tellus.

Cras pharetra augue nisl, quis pretium neque rhoncus sit amet. Nam id metus et ligula tincidunt aliquet. Sed molestie ante neque, in aliquet nunc ultrices laoreet. Praesent non nibh non justo aliquam commodo. Aliquam lacus elit, placerat at lacinia ut, iaculis in turpis. Fusce sodales lobortis felis, sed condimentum ex molestie vel. Nullam sit amet facilisis mi.
ncidunt sed nisi. Ut dapibus a sapien id dictum. Etiam euismod lacus non rhoncus tincidunt. Curabitur vestibulum urna eget risus vestibulum, ac gravida nisi lobortis. Curabitur in laoreet arcu, et vulputate lacus. Morbi vel pulvinar est. Vestibulum tincidunt porttitor convallis. Duis porttitor ac justo et sollicitudin. Mauris ex nisl, cursus in ante ac, maximus ornare dolor. Nulla vulputate nisl eget accumsan fringilla. Nunc hendrerit tristique elit consequat condimentum.

Pellentesque varius felis purus, nec cursus mauris iaculis quis. Integer erat neque, bibendum sed laoreet eu, tempor in velit. Aliquam sagittis tortor non nibh egestas, a feugiat arcu luctus. Pellentesque fermentum condimentum cursus. Ut accumsan orci nec facilisis mollis. Nam porttitor laoreet mattis. Nulla vehicula condimentum neque ac maximus. Suspendisse suscipit lorem mi, ut mollis metus porta vel. Mauris pretium, sem mattis lobortis mattis, enim risus pellentesque dui, eget laoreet libero orci sed orci. Mauris pulvinar sem massa, sed tincidunt neque porta nec. Mauris et lacus ut mauris dapibus faucibus vel et diam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam id eleifend augue. Morbi feugiat, nisl vitae pharetra bibendum, enim sapien vestibulum augue, non pretium quam ante pulvinar lacus. Duis fringilla sem vitae blandit blandit. Nunc viverra sed nisi ut bibendum.

Nulla vehicula quam vitae ex molestie elementum. Maecenas ac mattis turpis, et malesuada urna. Praesent dictum lorem vel diam pretium, et pretium libero hendrerit. Donec nec neque id lorem auctor vulputate vel nec nisl. Proin laoreet sapien sit amet enim tempus vestibulum. Quisque eros lacus, congue ac vestibulum commodo, euismod a quam. Integer volutpat lacinia est. Nulla turpis mauris, sodales quis lectus vitae, dictum feugiat arcu. Integer tincidunt ultricies est et accumsan. Donec feugiat dapibus enim, ac ornare tortor sodales in. Aliquam ut consectetur nisl, ut hendrerit ligula. Sed pharetra nec ex viverra aliquet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam finibus viverra mollis. Ut eu justo at massa dictum viverra.

Suspendisse quis sagittis eros. Quisque sodales mi at nisi volutpat tincidunt. In sollicitudin, ipsum quis vestibulum hendrerit, orci urna molestie felis, sed fringilla risus urna et magna. In enim diam, malesuada id venenatis sit amet, consequat vitae neque. Aenean nec bibendum odio, quis consectetur elit. Phasellus in lacus vel mi tempus imperdiet. Nam eget nunc id turpis vestibulum lobortis non vitae quam. Donec laoreet sagittis sem, vel pretium mauris sodales quis. Morbi molestie tempus tristique. Vivamus vitae cursus enim. Donec metus purus, bibendum in odio scelerisque, venenatis laoreet odio.

In mollis felis vel erat efficitur, vel lacinia erat sodales. Sed et sodales tortor, sed scelerisque arcu. Nullam laoreet sapien non aliquam hendrerit. Mauris et sem elementum, vulputate elit tristique, hendrerit odio. Nulla at nibh ac enim auctor pharetra ac nec mi. Morbi gravida nec dui quis volutpat. Sed euismod semper venenatis. Quisque elementum orci id quam blandit pellentesque. Morbi consectetur lectus sem, tincidunt ultricies mi rhoncus vel. Mauris commodo bibendum quam, nec sodales orci placerat nec. Vestibulum vel cursus massa. Phasellus placerat eu mauris commodo dapibus. Praesent id scelerisque nisl. Nunc eleifend sed nibh eu laoreet. Aenean vitae ornare urna, sit amet pretium nisl.

Fusce non condimentum purus. Vestibulum felis dolor, luctus a mauris ac, tincidunt faucibus lorem. Aliquam posuere augue in consectetur fermentum. Donec fermentum orci ut hendrerit consectetur. Curabitur dignissim tempor erat, eget aliquet magna rutrum luctus. Fusce pulvinar finibus vulputate. Phasellus sed dui erat. Cras dolor orci, aliquet eu purus at, pulvinar viverra lectus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed laoreet vulputate elit, at rutrum tellus accumsan a. Etiam iaculis massa ut libero pharetra, quis tempor nisi consectetur. Phasellus elementum leo eu tincidunt ullamcorper. Cras sollicitudin tellus lacus, eu convallis eros aliquam eget. Ut quis ultricies lectus, efficitur efficitur quam.

Aliquam erat volutpat. Sed dapibus ac tellus a accumsan. Nunc at rhoncus dolor. Curabitur et sem vel elit mattis laoreet a non libero. Donec magna elit, vulputate sed nunc in, ultrices bibendum arcu. Etiam tempor vestibulum purus quis mollis. Proin mattis orci sollicitudin urna eleifend malesuada. Proin porta elementum elit, id tempor ipsum gravida vel. Aenean cursus tristique nisl at egestas. Sed ac magna nec metus congue pharetra vel varius dui. Fusce et odio ac enim interdum cursus. Curabitur vehicula sem sit amet efficitur lacinia. Donec eu eros sollicitudin dui tincidunt maximus vehicula ut diam. Morbi euismod et metus non efficitur.

Quisque fringilla quam mi, non rutrum nunc porta id. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent et semper lectus. Curabitur porttitor felis interdum turpis dapibus, at consequat erat molestie. Vivamus nunc magna, pharetra quis eros nec, viverra consectetur eros. Etiam porttitor imperdiet risus id iaculis. Maecenas tincidunt arcu ut mauris vestibulum, sed porttitor quam mattis. Sed bibendum, nulla eu elementum ultrices, neque lacus lobortis mi, eu placerat justo quam non nisl. Aenean imperdiet imperdiet tristique. Duis pretium nulla at turpis commodo facilisis.

Donec sagittis justo vel malesuada blandit. Vestibulum tincidunt sem odio, a eleifend erat euismod ac. Praesent et magna orci. Nunc elementum metus erat, sed lobortis libero consequat id. Donec elementum cursus ipsum, at scelerisque nibh vehicula nec. Aenean commodo diam cursus laoreet porta. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec et bibendum nunc. Nulla viverra consectetur commodo. Nulla dapibus mi egestas risus vulputate consequat. Vestibulum nec bibendum diam.

Quisque vel scelerisque arcu. Ut lorem sem, mattis a mattis non, rhoncus eget sapien. In pharetra, ligula nec scelerisque facilisis, velit orci varius massa, ac vehicula nisl dolor quis felis. Praesent sit amet purus elit. Maecenas blandit lacus dui, nec maximus leo tristique vitae. Vivamus non orci quis elit ullamcorper scelerisque. Phasellus congue a nunc et mattis. Proin pulvinar leo quis odio convallis, id imperdiet sem efficitur. Quisque at mi commodo, efficitur risus quis, pharetra sapien. Morbi ligula risus, pharetra pellentesque pulvinar ut, fermentum ac sapien.

Duis tempus mauris non ex finibus porttitor. Ut rutrum pretium convallis. Ut vel blandit odio, vitae malesuada sem. Praesent molestie molestie neque sed ultrices. Nulla facilisi. Donec arcu massa, accumsan vitae eleifend sit amet, pretium in tortor. Maecenas interdum volutpat sollicitudin. Donec sodales tristique ex, posuere tincidunt est viverra et. Vivamus eget metus nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec lobortis massa et sodales tempus. Cras egestas ante vitae ipsum pharetra rutrum. Duis cursus diam sed felis sollicitudin, non porta quam laoreet. Praesent non rhoncus quam. Praesent at placerat orci, eu rutrum mauris.

Suspendisse fermentum, urna id malesuada volutpat, nulla diam varius mauris, eget euismod dolor tortor id augue. Integer suscipit varius magna vitae aliquam. Pellentesque vel sapien eu ligula pulvinar lacinia. Donec sodales nisi quis enim ullamcorper efficitur. Duis nec ante nisi. Nulla sit amet mi eros. Integer non purus turpis. Donec eu est nec nulla tempor facilisis quis et nisl. Nulla convallis, augue at tincidunt posuere, orci nibh ornare tortor, id vulputate augue augue et lacus. Aenean auctor rhoncus dolor, ut hendrerit dui euismod posuere. Nulla rutrum sem elit, non finibus quam venenatis ut. Nullam pretium rhoncus tortor a tempor. Nullam fermentum justo id mattis mollis. Nullam vel ultrices lacus. Nam dapibus vulputate arcu, at feugiat ligula elementum id.

Vivamus non eros iaculis ex tincidunt consequat eu placerat eros. Mauris sodales, odio ut ultrices finibus, nisi velit posuere sem, eget porta ligula erat vitae enim. Vestibulum lobortis tortor eu diam congue auctor. Proin urna eros, rutrum non quam vitae, tincidunt gravida dolor. Nullam sit amet odio a est rhoncus commodo. Morbi pulvinar tellus ut nisi lobortis egestas. Sed consequat elementum nibh, a auctor nunc viverra non. Suspendisse potenti. Morbi vitae velit tempus, efficitur dui at, gravida quam. Duis facilisis sodales dui, et consectetur enim pharetra ac. Quisque eu fermentum risus, a tempus dui. In sed pharetra ante. Donec viverra est lectus, non tristique nulla cursus ac. Donec tortor augue, commodo ullamcorper lacus sit amet, porttitor vulputate sapien. In condimentum non lacus sed malesuada. Nam eget justo ut nibh aliquet gravida.

Donec odio eros, laoreet et ipsum non, fermentum volutpat leo. Phasellus ex ipsum, gravida a pharetra in, consequat vitae nisl. Fusce erat sapien, tristique ac tincidunt sit amet, lobortis nec turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed sit amet enim neque. In hac habitasse platea dictumst. Sed sit amet ipsum semper, facilisis nisi quis, egestas mi. Aenean venenatis purus in libero sagittis, nec interdum est vehicula. Cras finibus nibh vitae quam vulputate blandit. Morbi eu accumsan odio. Donec eu cursus eros. Sed tristique dolor ut gravida bibendum. Duis nec lacus varius, varius dolor nec, volutpat arcu. Proin cursus cursus dolor ullamcorper sodales.

Curabitur blandit consequat gravida. Duis laoreet venenatis justo mollis tempus. Maecenas nec tellus sapien. Nunc pretium mattis sollicitudin. Morbi nec purus sed mi consequat hendrerit. Nulla molestie leo id ipsum eleifend, et gravida mauris sagittis. Nullam non lorem et dolor sollicitudin ornare.

Nullam faucibus metus non massa efficitur, id consectetur nisi elementum. Mauris eu dictum est, sed porta metus. Donec blandit ultrices euismod. Morbi efficitur auctor leo, nec molestie lorem hendrerit sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce quis pharetra eros. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque eu lacinia ante. Nunc rhoncus tellus ac lacus elementum eleifend. Integer bibendum bibendum ultrices. In pretium, risus at laoreet elementum, nulla magna viverra ante, vel tristique mi nisl nec lacus. Mauris posuere massa et lorem tempus, ut mattis erat congue.

Vivamus hendrerit elit vitae blandit consectetur. Cras vestibulum eget mi eget eleifend. Maecenas blandit tellus et tellus ultricies, ultricies suscipit nunc dapibus. Sed cursus pulvinar pharetra. Etiam facilisis, tortor sed ornare hendrerit, mauris nisl rhoncus tellus, ut varius magna tortor quis massa. Aliquam eget vulputate turpis, congue consequat orci. Curabitur ultricies ultricies diam. Donec quis eros id ligula congue congue. Mauris eu ipsum massa. Pellentesque vitae tempus eros.

Vivamus sit amet diam ac nisl lacinia imperdiet nec eu justo. Phasellus pharetra leo eget purus venenatis sodales. Phasellus interdum convallis bibendum. Cras ultrices ac diam vestibulum egestas. Aenean urna mauris, cursus vel egestas ornare, dictum id elit. Proin dui arcu, ullamcorper et condimentum ut, euismod non massa. Praesent fringilla mauris vel ante malesuada fermentum sed et tellus.

